const SectionTypes = {
  MOTORWAY: "MOTORWAY",
  HIGHWAY: "HIGHWAY",
  TOLL_ROAD: "TOLL_ROAD",
  TUNNEL: "TUNNEL",
  TRAFFIC: "TRAFFIC",
  TRAVEL_MODE: "TRAVEL_MODE",
  UNPAVED: "UNPAVED",
  OTHER: "OTHER",
  LANES: "LANES"
};

export default SectionTypes;
