export default {
  NAVIGATION_NOT_STARTED: "NAVIGATION_NOT_STARTED",
  NAVIGATION_STARTED: "NAVIGATION_STARTED",
  NAVIGATION_STOPPED: "NAVIGATION_STOPPED",
  DESTINATION_REACHED: "DESTINATION_REACHED"
};
