const SectionTypes = {
  MOTORWAY: "MOTORWAY",
  HIGHWAY: "HIGHWAY",
  TOLL: "TOLL",
  TUNNEL: "TUNNEL",
  TRAFFIC: "TRAFFIC",
  TRAVEL_MODE: "TRAVEL_MODE",
  UNPAVED: "UNPAVED",
  OTHER: "OTHER",
  LANES: "LANES",
  SPEED_LIMIT: "SPEED_LIMIT"
};

export default SectionTypes;
