import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  "en-US": {
    noApiKey: "Set the API key property to view map",
    stops: "stops",
    street: "Street",
    satellite: "Satellite",
    location: "Location",
    traffic: "Traffic",
    locationServicesUnavailable:
      "Location services not supported for this device",
    locationServicesNotEnabled:
      "Location services not enabled. Enable to use your current location",
    ok: "OK",
    go: "Go",
    exit: "Exit",
    skip: "Skip",
    arrived: "Arrived",
    guidanceAnnouncementTemplate: "{maneuverText} in {distance} {units}",
    guidanceAnnouncementOntoStreetTemplate:
      "{maneuverText} in {distance} {units} onto {street}",
    consecutiveInstructionTemplate: "Then {maneuverText}",
    arrivalStraightAhead: "Destination is straight ahead",
    arrivalLeft: "Destination on the left",
    arrivalRight: "Destination on the right",
    markedLocation: "Marked location",
    continueWalking: "Continue walking",
    ARRIVING: "You will arrive at your destination",
    ARRIVE: "You have arrived at your destination",
    ARRIVE_LEFT: "You have arrived. Your destination is on the left",
    ARRIVE_RIGHT: "You have arrived. Your destination is on the right",
    DEPART: "Start driving",
    DEPART_PEDESTRIAN: "Start walking",
    STRAIGHT: "Keep straight on",
    KEEP_RIGHT: "Keep right",
    BEAR_RIGHT: "Bear right",
    TURN_RIGHT: "Turn right",
    SHARP_RIGHT: "Turn sharp right",
    KEEP_LEFT: "Keep left",
    BEAR_LEFT: "Bear left",
    TURN_LEFT: "Turn left",
    SHARP_LEFT: "Turn sharp left",
    MAKE_UTURN: "Make a u-turn",
    ENTER_MOTORWAY: "Take the motorway",
    ENTER_FREEWAY: "Take the freeway",
    ENTER_HIGHWAY: "Take the highway",
    TAKE_EXIT: "Take the exit",
    MOTORWAY_EXIT_LEFT: "Take the left exit",
    MOTORWAY_EXIT_RIGHT: "Take the right exit",
    TAKE_FERRY: "Take the ferry",
    CAR_TRAIN: "Take the car train",
    ROUNDABOUT_CROSS: "Cross the roundabout",
    ROUNDABOUT_RIGHT: "At the roundabout take the exit on the right",
    ROUNDABOUT_LEFT: "At the roundabout take the exit on the left",
    ROUNDABOUT_BACK: "Go around the roundabout",
    TRY_MAKE_UTURN: "Try to make a U-turn",
    FOLLOW: "Follow",
    SWITCH_PARALLEL_ROAD: "Switch to the parallel road",
    SWITCH_MAIN_ROAD: "Switch to the main road",
    ENTRANCE_RAMP: "Take the ramp",
    WAYPOINT_LEFT: "You have reached the waypoint. It is on the left",
    WAYPOINT_RIGHT: "You have reached the waypoint. It is on the right",
    WAYPOINT_REACHED: "You have reached the waypoint",
    MERGE_LEFT_LANE: "Merge into the left lane",
    MERGE_RIGHT_LANE: "Merge into the right lane",
    AHEAD_KEEP_RIGHT: "Keep right ahead",
    AHEAD_RIGHT_TURN: "Make a right turn ahead",
    AHEAD_KEEP_LEFT: "Keep left ahead",
    AHEAD_LEFT_TURN: "Make a left turn ahead",
    AHEAD_UTURN: "Make a u-turn ahead",
    AHEAD_EXIT: "Exit ahead",
    AHEAD_EXIT_RIGHT: "Exit right ahead",
    AHEAD_EXIT_LEFT: "Exit left ahead",
    AHEAD_TAKE_FERRY: "Take the ferry ahead",
    WAYPOINT_APPROACH: "Approaching waypoint",
    CROSS_BORDER: "Cross the border",
    TOLLGATE: "Approach the toll booth"
  },
  nl: {
    noApiKey: "Vul de API key property in om de map te gebruiken",
    stops: "haltes",
    street: "Straat",
    satellite: "Satelliet",
    location: "Plaats",
    traffic: "Verkeer",
    locationServicesUnavailable:
      "Locatieservices worden niet ondersteund voor dit apparaat",
    locationServicesNotEnabled:
      "Locatieservices zijn niet ingeschakeld. Schakel in om uw huidige locatie te gebruiken",
    ok: "OK",
    go: "Ga",
    exit: "Afslag",
    skip: "Overslaan",
    arrived: "Aangekomen",
    guidanceAnnouncementTemplate: "{maneuverText} in {distance} {units}",
    guidanceAnnouncementOntoStreetTemplate:
      "{maneuverText} in {distance} {units} naar {street}",
    consecutiveInstructionTemplate: "Daarna {maneuverText}",
    arrivalStraightAhead: "Bestemming is rechtdoor",
    arrivalLeft: "Bestemming aan de linkerkant",
    arrivalRight: "Bestemming aan de rechterkant",
    markedLocation: "Gemarkeerde plaats",
    ARRIVING: "Bestemming bijna bereikt",
    ARRIVE: "Bestemming bereikt",
    ARRIVE_LEFT: "Bestemming bereikt aan de linkerkant",
    ARRIVE_RIGHT: "Bestemming bereikt aan de rechterkant",
    DEPART: "Vertrek",
    STRAIGHT: "Ga rechtdoor",
    KEEP_RIGHT: "Houd rechts aan",
    BEAR_RIGHT: "Rechts afbuigen",
    TURN_RIGHT: "Rechts afslaan",
    SHARP_RIGHT: "Scherpe bocht naar rechts",
    KEEP_LEFT: "Houd links aan",
    BEAR_LEFT: "Links afbuigen",
    TURN_LEFT: "Links afslaan",
    SHARP_LEFT: "Scherpe bocht naar links",
    MAKE_UTURN: "Keer om",
    ENTER_MOTORWAY: "Ga de snelweg op",
    ENTER_FREEWAY: "Ga de snelweg op",
    ENTER_HIGHWAY: "Ga de snelweg op",
    TAKE_EXIT: "Neem de afslag",
    MOTORWAY_EXIT_LEFT: "Neem de afslag links",
    MOTORWAY_EXIT_RIGHT: "Neem de afslag rechts",
    TAKE_FERRY: "Neem de veerboot",
    ROUNDABOUT_CROSS: "Ga rechtdoor op de rotonde",
    ROUNDABOUT_RIGHT: "Ga rechts op de rotonde",
    ROUNDABOUT_LEFT: "Ga links op de rotonde",
    ROUNDABOUT_BACK: "Ga links op de rotonde",
    TRY_MAKE_UTURN: "Probeer om te keren",
    FOLLOW: "Volg",
    SWITCH_PARALLEL_ROAD: "Schakel over op parallelweg",
    SWITCH_MAIN_ROAD: "Schakel over op hoofdweg",
    ENTRANCE_RAMP: "Neem de oprit",
    WAYPOINT_LEFT: "Tussenpunt bereikt aan de linkerkant",
    WAYPOINT_RIGHT: "Tussenpunt bereikt aan de rechterkant",
    WAYPOINT_REACHED: "Je hebt je tussenpunt bereikt",
    AHEAD_KEEP_RIGHT: "Verderop rechts aanhouden",
    AHEAD_RIGHT_TURN: "Verderop rechtsaf",
    AHEAD_KEEP_LEFT: "Verderop links aanhouden",
    AHEAD_LEFT_TURN: "Verderop links aanhouden",
    AHEAD_UTURN: "Verderop omkeren",
    AHEAD_EXIT: "Neem verderop de afslag",
    AHEAD_EXIT_RIGHT: "Neem verderop de afslag naar rechts",
    AHEAD_EXIT_LEFT: "Neem verderop de afslag naar links",
    AHEAD_TAKE_FERRY: "Neem verderop de veerboot",
    WAYPOINT_APPROACH: "Tussenpunt bijna bereikt"
  }
});

export default strings;
